apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: httpbin-rt-443
  namespace: httpbin
  labels:
    expose: "true"
spec:
  hosts:
    - '*'
  virtualGateways:
    - name: cluster1-north-south-gw-443
      namespace: istio-gateways
      cluster: cluster1
  workloadSelectors: []
  http:
    - name: httpbin
      matchers:
      - uri:
          exact: /get
      - uri:
          prefix: /callback
      - uri:
          prefix: /logout
      - uri:
          prefix: /anything
      forwardTo:
        destinations:
          - ref:
              name: httpbin-vd
              namespace: httpbin
            kind: VIRTUAL_DESTINATION
            port:
              number: 8000
            subset:
              version: v1
            weight: 50
          - ref:
              name: httpbin-vd
              namespace: httpbin
            kind: VIRTUAL_DESTINATION
            port:
              number: 8000
            subset:
              version: v2
            weight: 50